### PR TITLE
Some changes to support installing the gem in macOS Big Sur

### PR DESCRIPTION
**Pull request by srbarrios**
Hi guys,

I was tired of not being able to run my tests in my Macbook, my test framework is using the gem of twopence as a dependency.

I succeed installing the gem not without some changes in this code:
```
oscar@Oscar twopence % gem info twopence

*** LOCAL GEMS ***

twopence (0.3.10)
    Author: SUSE
    Homepage: http://www.suse.com
    License: GPL-2.0
    Installed at: /usr/local/lib/ruby/gems/2.7.0

    Twopence test executor
```

Please, could you take a look?
Even if working here, I'm sure it could be plenty of mistakes and things to code it better...

### CODE REVIEW

**Comment by srbarrios** [comment]
In fact, not working yet.... 🤷‍♂️ 

```
oscar@Oscar-2 examples % irb
irb(main):001:0> require "twopence"
=> true
irb(main):003:0> $target = Twopence::init("suma-41-srv.mgr.prv.suse.net")
Error while initializing library: Invalid target specification
=> nil
irb(main):004:0> $target = Twopence::init("ssh:suma-41-srv.mgr.prv.suse.net")
=> #<Twopence::Target:0x00007fde2214de00>
irb(main):005:0>  $target.test_and_print_results('ls -l')
=> [-2, 0, 0]
```

**Comment by srbarrios** [comment]
Just a reminder :) 
In order to test it with an IP by SSH, remember that you need to configure your system to use ssh key instead of user/password.

**Comment by Bischoff** [comment]
Looks good to me, very clean. Thanks for the great contribution. A few questions and remarks:

1. Why `ruby_ppoll()` name? This is a C function, I don't see the connection with ruby.

2. I'm not a big fan of functions being defined in `.h` header files. Move it to a C file, only leaving the declaration there?

3. As it's a huge improvement, feel free to switch to `0.4.0`.

4. Maybe describe changes in changelog?

**Comment by srbarrios** [comment]
Changes made. Tested in MacOS and Tumbleweed.

**Pull request merged**
