### PR TITLE
docs: Fix README issues

### PR DESCRIPTION
**Pull request by nodeg**
This will fix several issues with the README:

* grammar
* typos
* linting

### CODE REVIEW

**Review by Bischoff — APPROVED** [review]
thank you

**Comment by nodeg** [comment]
I see the following error on openSUSE Tumbleweed and Leap 15.4:

```bash
dgedon@localhost:~/git/twopence> sudo zypper install libssh-devel ruby-devel rubygem-rake-compiler python-devel
[sudo] password for root: 
Loading repository data...
Reading installed packages...
'rubygem-rake-compiler' not found in package names. Trying capabilities.
No provider of 'rubygem-rake-compiler' found.
```

Do we really need `'rubygem-rake-compiler`?

**Comment by Bischoff** [comment]
> Do we really need `'rubygem-rake-compiler`?

Try to compile without. I think it was needed for including native C code. But I am not sure anymore.

> We should also mention to install `gcc` since it was not already installed in a blank Tumbleweed/Leap 15.4

Right.

**Comment by nodeg** [comment]
I did a compilation without it in my [other PR](https://github.com/openSUSE/twopence/pull/68#issuecomment-1087505565) and it worked.

**Pull request merged**
