### PR TITLE
append a 2.7 for compiling in non SUSE systems

### PR DESCRIPTION
**Pull request by MalloZup**

### CODE REVIEW

**Comment by MalloZup** [comment]
this PR fix : 
https://github.com/openSUSE/twopence/issues/45
https://github.com/openSUSE/twopence/issues/44

**Comment by MalloZup** [comment]
tested on fedora : "Fedora 23 (Server Edition)"

**Comment by MalloZup** [comment]
without the PR we have this : 

cc -fPIC -I/usr/include/python -I../library -Wall -O2 -g   -c -o extension.o extension.c
In file included from extension.c:21:0:
extension.h:25:20: fatal error: Python.h: No such file or directory
compilation terminated.

**Comment by MalloZup** [comment]
@Bischoff  @okirch  do you see any disavantage doing this? 

i could maybe introduce a $OS variable, and insert an if , but for me seems more clear like that.

**Comment by thehejik** [comment]
Cleanest solution will be something like "configure" file for generating Makefiles dependent on used distro. On ubuntu "update-alternatives --config python" could help to avoid versions in python paths (it should create symlinks without version resolution).

**Pull request merged**
